"""
Regenerate requirements.txt from the installed environment
==========================================================

pyproject.toml lists what the project needs directly (no versions).
requirements.txt pins the exact versions of those packages AND of everything
they pull in, as installed here, so the environment can be rebuilt.

Starting from the dependencies in pyproject.toml (with every extra), this
script follows each installed package's declared requirements, keeping only
the ones that apply to this machine (Python version, OS, requested extras).
Nothing is downloaded: it reads the metadata of the installed packages.
Needs Python >= 3.11 (tomllib), unlike the package itself.

Usage:
    .venv/bin/python scripts/freeze_requirements.py > requirements.txt
"""

import sys
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

import tomllib
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

PYPROJECT = Path(__file__).resolve().parent.parent / "pyproject.toml"


def roots() -> list[Requirement]:
    project = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))["project"]
    deps = list(project["dependencies"])
    for extra in project.get("optional-dependencies", {}).values():
        deps += extra
    return [Requirement(d) for d in deps]


def closure(start: list[Requirement]) -> dict[str, str]:
    """name -> installed version, for every package reachable from `start`."""
    pinned: dict[str, str] = {}
    seen: set[tuple[str, frozenset[str]]] = set()
    todo = [(r, frozenset()) for r in start]
    while todo:
        req, parent_extras = todo.pop()
        # A requirement applies only if its marker matches this machine, and,
        # for "; extra == 'x'" markers, if the parent was asked with that extra.
        if req.marker and not any(req.marker.evaluate({"extra": e}) for e in parent_extras or {""}):
            continue
        name = canonicalize_name(req.name)
        key = (name, frozenset(req.extras))
        if key in seen:
            continue
        seen.add(key)
        try:
            dist = distribution(req.name)
        except PackageNotFoundError:
            sys.exit(f"{req.name} is required but not installed: install the project first "
                     "(pip install -e '.[dev,ui]').")
        pinned[name] = dist.version
        todo += [(Requirement(r), frozenset(req.extras)) for r in dist.requires or []]
    return pinned


def main():
    pinned = closure(roots())
    print("# Exact versions of the project's dependencies and everything they pull in,")
    print(f"# as installed on {sys.platform} with Python {sys.version_info.major}.{sys.version_info.minor}.")
    print("# Generated by scripts/freeze_requirements.py from pyproject.toml: do not edit by hand.")
    for name in sorted(pinned):
        print(f"{name}=={pinned[name]}")


if __name__ == "__main__":
    main()
